/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.8.0
 *
 * Project: 'RPMSG_TTY_CMSIS-RTOS2_M4+Target_1' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "iMX7D_M4.h"

/* ARM::AMP:RPMSG&OpenAMP@1.0.0 */
#define RTE_AMP_RPMSG_OPENAMP
/* ARM::CMSIS-Compiler:STDERR:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_Custom         /* CMSIS-Compiler STDERR: Custom */
/* ARM::CMSIS-Compiler:STDIN:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
#define RTE_CMSIS_Compiler_STDIN_Custom          /* CMSIS-Compiler STDIN: Custom */
/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS-Compiler:TTY:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_TTY                   /* CMSIS-Compiler TTY */
#define RTE_CMSIS_Compiler_TTY_Custom            /* CMSIS-Compiler TTY: Custom */
/* ARM::CMSIS:RTOS2:Keil RTX5&Library@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */


#endif /* RTE_COMPONENTS_H */
